### ISSUE TITLE
Could not find wilson_lower

### ISSUE THREAD

**Issue by SteveSpreadborough** [PublicHealthEngland/PHEindicatormethods#25]
Hi Georgie, I'm getting an error from the below code saying` "Error in wilson_lower(df$obs, df$pop) : could not find function "wilson_lower"`

```
df <- data.frame(area = rep(c("Area1","Area2","Area3","Area4"), each=3),
                 obs = c(5,82,9,48, 6500,8200,10000,10000,8,7,750,900),
                 pop = rep(c(100,10000,10000,10000), each=3))

wilson_l <- wilson_lower(df$obs, df$pop)
```
I've updated the package to version 1.1.3 from github. Using `wilson_l <- PHEindicatormethods:::wilson_lower(df$obs, df$pop)` gives the error `"Error: 'wilson_lower' is not an exported object from 'namespace:PHEindicatormethods'"`, but using three colons works: `wilson_l <- PHEindicatormethods:::wilson_lower(df$obs, df$pop) `

**Comment by PHEgeorginaanderson** [comment]
Hi Steve - I know you've worked this out now but to complete the GitHub record...

The byars and wilson functions were moved to the package utilities in release 1.1.1 as these were causing confusion for some users who were using these directly rather than the using the phe_ prefixed functions that call them.  If required, the byars and wilson functions can still be called directly using the following (3 colon) syntax:

wilson_l <- PHEindicatormethods:::wilson_lower(df$obs, df$pop)

Please see the NEWS file entry for release 1.1.1

Thanks
Georgie
